### PR TITLE
chore: release v4.2.2

### PR DESCRIPTION
**Pull request by michael-siek**
Issue:

### CODE REVIEW

**Comment by michael-siek** [comment]
# Release Audit 
- [x] https://github.com/dequelabs/axe-core-maven-html/pull/166

**Review by AdnoC — APPROVED** [review]

**Comment by dylanb** [comment]
reviewed

**Review by WilcoFiers — APPROVED** [review]
## Release Audit
- [ ] https://github.com/dequelabs/axe-core-maven-html/pull/166 Should have been "fix"

**Comment by dylanb** [comment]
reviewed

**Pull request merged**
