### PR TITLE
chore: use public npm registry

### PR DESCRIPTION
**Pull request by michael-siek**
## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Code is reviewed for security

### CODE REVIEW

**Review by stephenmathieson — APPROVED** [review]
I don't think we need the lockfile here either, but it doesn't hurt anything 🤷‍♂️

**Review by WilcoFiers — DISMISSED** [review]
Far better to just make sure CI doesn't have access to Agora. I'm not so sure about using npmrc files to enforce this.

**Comment by michael-siek** [comment]
@WilcoFiers I don't see anywhere in CI where it has access to Agora.

**Comment by stephenmathieson** [comment]
@WilcoFiers the purpose of this is to prevent _us_ from accidentally using Agora when we install deps here.

**Pull request merged**
