### PR TITLE
[WIP]fix(selenium): parse received partial results before finishRun

### PR DESCRIPTION
**Pull request by Zidious**
Make sure all partial results are JSON are not a type of string

### CODE REVIEW

**Review by stephenmathieson — CHANGES_REQUESTED** [review]
Tests?

**Comment by Zidious** [comment]
> Tests?

Whoops - will add 🤦

**Comment by Zidious** [comment]
This was a very unique situation: https://github.com/dequelabs/axe-devtools-maven-html/issues/509, we already have nested iframe tests but specifically for that issue we have had to make sure the results are parsed to JSON

**Comment by Zidious** [comment]
No longer required! Closing.

**Pull request closed without merging**
