### PR TITLE
Updated AxeBuilder, AxeReporter, and AxeResult class Instantiation

### PR DESCRIPTION
**Pull request by jonreding2010**
-Added Object Oriented classes to better access scan result properties.
-Put Builder functionality into it's own class
-GetContent and report functionality are now in the AxeReporter class
-Organized new classes for easy navigation and organization
-Updated the scan.js file inputs to take in an object during .executeAsyncScript execution

-Added Results directory for json and txt file test reporting
-Added tests for all new functionality
-Added copy of test file of Example Test but uses new functionality
-Added html pages so testing works when webdriver is added

-No changes were made to Axe or ExampleTest files
-Changes were based on [https://github.com/TroyWalshProf/SeleniumAxeDotnet](https://github.com/TroyWalshProf/SeleniumAxeDotnetl)

### Reviewer Checks

 - [ ] Follows the commit message policy, appropriate for next version
 - [ ] Has documentation updated, a DU ticket, or requires no documentation change
 - [ ] Includes new tests, or was unnecessary
 - [ ] Code is reviewed for security by: << Name here >>

### CODE REVIEW

**Comment by TroyWalshProf** [comment]
@stephenmathieson - Any idea who could be assigned to review this?

**Comment by WilcoFiers** [comment]
@TroyWalshProf we have reviewed this. We very much appreciate the work, but because this pull request has breaking changes we have to plan this a little more carefully then we would if it was just a new feature.

We have ourselves been planning for a major overhaul for of this package. We haven't fully planned this out yet, but we expect it will include a number of breaking changes. To avoid doing two major release in a relatively short period of time, I don't think we can release this. So I want to get your thoughts on how you'd like to see this work being used. The way I see it, there are two options

1. We can either merge this, make this a prerelease version of 4.0 so that folks can start using it. That would come with the rather substantial caveat that there will probably be more breaking changes going into 4.0, so the 4.0 prerelease snapshot would at some point have more breaking changes in it.

2. We could leave this pull request where it is for now until we know the other changes that we want to make. We'll try to prioritise it, so that we can have all the breaking changes in it, and once that's all resolved do a prerelease snapshot of 4.0.

The timeline for 4.0 is currently not yet decided, but it looks like it might be in the 3 to 5 months range. If you're happy to wait for this code to make it in, I'd prefer option 2, but if you'd like to have this released soon we should probably just review and merge this, get it out as a prerelease, with the knowledge that further breaking changes are coming.

**Comment by TroyWalshProf** [comment]
@WilcoFiers option 2 sounds like the best option to me.
Note, I am maintaining Dotnet binding at https://github.com/TroyWalshProf/SeleniumAxeDotnet, which is where the vast majority of this pull requests changes came from. 
If there are any changes you are doing for the Java binding that you think would be good for the Dotnet implementation please feel free to let me know.

@jason-edstrom and @jonreding2010  this may push back your accessibility changes a little bit.

**Comment by WilcoFiers** [comment]
Thank you for your patients @TroyWalshProf. We'll definitely prioritise this, but it may still be a little while.

**Comment by AdnoC** [comment]
Was merged as part of https://github.com/dequelabs/axe-core-maven-html/pull/75

**Comment by AdnoC** [comment]
Notable change was the results package, which was replaced by one we had for a closed source project that now depends on this.

**Pull request closed without merging**
