### PR TITLE
fix: improve result toString implementation to be more actionable

### PR DESCRIPTION
**Pull request by lisli1**
Issue: Currently, the `toString` methods for `Check`s, `CheckedNode`s, and `Node`s in Selenium and Playwright don't provide a lot of information to the user during accessibility testing. This PR overrides the `toString` methods in these instances, similar to how it's done in [Rule.java](https://github.com/dequelabs/axe-core-maven-html/blob/5fe065d85e01a0c6b0f0a252554941cd01c62f42/selenium/src/main/java/com/deque/html/axecore/results/Rule.java#L92), to provide more actionable output to the user.

### CODE REVIEW

**Comment by dbjorge** [comment]
Specifically, this was motivated by an issue we noticed while authoring the examples in the new [Playwright for Java Accessibility Testing docs](https://playwright.dev/java/docs/next/accessibility-testing) where test assertions of the form

```java
assertEquals(Collections.emptyList(), accessibilityScanResults.getViolations());
```

...currently produce output which isn't actionable because it doesn't contain any information about the location of the issue on the page.

**Comment by Zidious** [comment]
:wave: Hey @lisli1 @dbjorge !

This is awesome - will review as soon as possible

**Review by Zidious — APPROVED** [review]
Thank you @lisli1 and @dbjorge 
LGTM

**Comment by Zidious** [comment]
- [ ] reviewed for security

**Pull request merged**
